project:
  type: website
  output-dir: docs


website:
  title: "Lab_6"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
format:
  html:
    self-contained: true
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

